### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by mkyriak** [tkchafin/vcf2msa.py#4]
Hello and thank you for the tool!

I would like to use vcf2msa.py on a multi-sample `vcf` generated by `graphtyper` and I am working on a conda env where the python version is `Python 3.11.3` and I ran the command as follows:

`python vcf2msa.py -f Homo_sapiens_assembly38.fasta -v input_large.vcf.gz -R regions.txt`

The `regions.txt` contains only the regions of interest in the genome which were used to call variants.
It has the following format:
chr1:2050-10500
chr2:26696531-26696821
......

The error I am getting is:

`Traceback (most recent call last):
  File "/home/mkyriakidou/software/vcf2msa.py/vcf2msa.py", line 691, in <module>
    main()
  File "/home/mkyriakidou/software/vcf2msa.py/vcf2msa.py", line 20, in main
    params = parseArgs()
             ^^^^^^^^^^^
  File "/home/mkyriakidou/software/vcf2msa.py/vcf2msa.py", line 646, in __init__
    if self.regfile and len(self.region) > 0:
                        ^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()`

Thank you in advance for your time and help!

**Comment by tkchafin** [comment]
Hi @mkyriak! I just merged a fix for this (and some other changes; thanks to @YongLiedu!!). Note that the installation now requires PyVCF3 for Python>3.10. Please let me know if it is working for you now. -Tyler

**Comment by mkyriak** [comment]
Hi @tkchafin ! Thank you for your rapid response!
I removed the previous directory and I cloned the new one. There are two things I noticed:

1. If there are no SNVs found in a chromosome, I get the following error:

`Traceback (most recent call last):
  File "/home/mkyriakidou/software/vcf2msa.py/./vcf2msa.py", line 733, in <module>
    main()
  File "/home/mkyriakidou/software/vcf2msa.py/./vcf2msa.py", line 172, in main
    for rec in vfh.fetch(contig, nuc, nuc + 1):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mkyriakidou/mambaforge/envs/phylodynamics/lib/python3.11/site-packages/vcf/parser.py", line 631, in fetch
    self.reader = self._tabix.fetch(chrom, start, end)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pysam/libctabix.pyx", line 507, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region 'chr10:14649841-14649941'`

2. The second is about muscle:

`Traceback (most recent call last):
  File "/home/mkyriakidou/software/vcf2msa.py/./vcf2msa.py", line 733, in <module>
    main()
  File "/home/mkyriakidou/software/vcf2msa.py/./vcf2msa.py", line 228, in main
    this_pos = muscle_align(this_pos)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mkyriakidou/software/vcf2msa.py/./vcf2msa.py", line 423, in muscle_align
    stdout, stderr = muscle_cline(stdin=data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mkyriakidou/mambaforge/envs/phylodynamics/lib/python3.11/site-packages/Bio/Application/__init__.py", line 574, in __call__
    raise ApplicationError(return_code, str(self), stdout_str, stderr_str)
Bio.Application.ApplicationError: Non-zero return code 1 from 'muscle -clwstrict', message 'Invalid command line'`

The version of muscle I am using is:
`muscle --version
muscle 5.1.linux64 []`

**Comment by tkchafin** [comment]
I pushed a fix for the 2nd issue. Muscle doesn't seem to be accepting piped input, so to avoid excessive I/O operations I switched the alignment program the script uses to Clustal Omega. You can install with `conda install -c bioconda clustalo`. 

I can't replicate the first issue, can you confirm you are providing a VCF indexed with tabix?

**Comment by mkyriak** [comment]
Yes, I confirm that my vcf is compressed with `bgzip` and indexed with `tabix`.

After cloning the new repository, I managed to run `vcf2msa.py` successfully by providing a `txt` file with only the chromosomes that contain SNVs, without getting any of the previous errors.

I have one more question: will it be a good practice to concatenate all the MSA from all the contigs into one file for further analysis?

Thank you for your help and patience!

**Comment by tkchafin** [comment]
Glad you were able to get it to work. Will try to track down the issue with the invariant chromosomes later... 

As for concatenation, it depends on what you are trying to do. My use cases for this script have been that I want to infer some gene trees for various regions of the genome, then analyse use these gene trees as input for a method such as ASTRAL.

**Comment by mkyriak** [comment]
Thank you!

I see, in my case, I want to use SNVs detected from WGS data to run some phylodynamic models.

**Comment by mkyriak** [comment]
I wasn't sure if I should have opened another issue, but when generating the MSA, I got the following IUPAC symbols instead of nucleotides for each of my samples (K, M, R, S, W, Y).

For instance, some of the samples contain a C > T variant at one position (0/1) and some others are homozygous (0/0). This is specified by the genotype field in the VCF file. However, for all the samples, I am getting a "Y" symbol in the output MSA. This particular SNV is flagged as "LowQUAL" and I am not sure if I still can get the consensus and the MSA even from low quality variants?

**Edited**
I've just noticed that the same happens with the variants flagged as "PASS".


Thank you once again!
